export const roles = [
  {
    code: "admin",
    name: "Administrator",
    description: "Akses penuh ke modul operasional dan konfigurasi sistem.",
  },
  {
    code: "teknisi",
    name: "Teknisi",
    description: "Akses untuk PSB, pekerjaan lapangan, dan penagihan lapangan.",
  },
  {
    code: "finance",
    name: "Finance",
    description: "Akses untuk billing, pembayaran, kas, dan laporan keuangan dasar.",
  },
  {
    code: "customer",
    name: "Customer",
    description: "Akses portal pelanggan untuk melihat layanan, invoice, dan tiket.",
  },
] as const;

const permissionKeys = [
  "auth.login",
  "auth.logout",
  "auth.me.read",
  "auth.profile.update",
  "auth.password.change_self",

  "users.list",
  "users.read",
  "users.create",
  "users.update",
  "users.activate",
  "users.deactivate",
  "users.reset_password",

  "roles.list",
  "roles.read",
  "roles.create",
  "roles.update",
  "roles.assign",
  "permissions.list",

  "settings.general.read",
  "settings.general.update",

  "prospects.list",
  "prospects.read",
  "prospects.create",
  "prospects.update",
  "prospects.delete",
  "prospects.assign_plan",
  "prospects.set_installation_date",
  "prospects.set_coordinates",
  "prospects.set_pppoe_username",
  "prospects.set_pppoe_password",
  "prospects.view_pppoe_password",
  "prospects.copy_pppoe_password",
  "prospects.mark_surveyed",
  "prospects.mark_scheduled_installation",
  "prospects.mark_installed",
  "prospects.mark_cancelled",
  "prospects.reject",
  "prospects.activate",
  "prospects.convert_to_customer",

  "customers.list",
  "customers.read",
  "customers.update",
  "customers.delete",
  "customers.view_customer_code",

  "customer_addresses.list",
  "customer_addresses.read",
  "customer_addresses.create",
  "customer_addresses.update",
  "customer_addresses.delete",

  "customer_accounts.list",
  "customer_accounts.read",
  "customer_accounts.create",
  "customer_accounts.reset_password",
  "customer_accounts.disable",
  "customer_accounts.enable",
  "customer_accounts.change_password_self",

  "service_plans.list",
  "service_plans.read",
  "service_plans.create",
  "service_plans.update",
  "service_plans.deactivate",

  "subscriptions.list",
  "subscriptions.read",
  "subscriptions.create",
  "subscriptions.update",
  "subscriptions.activate",
  "subscriptions.suspend",
  "subscriptions.resume",
  "subscriptions.terminate",
  "subscriptions.upgrade",
  "subscriptions.downgrade",
  "subscriptions.set_prorate",
  "subscriptions.set_billing_anchor",
  "subscriptions.view_pppoe_password",
  "subscriptions.copy_pppoe_password",
  "subscriptions.update_pppoe_password",

  "work_orders.list",
  "work_orders.read",
  "work_orders.create",
  "work_orders.assign",
  "work_orders.update",
  "work_orders.close",
  "work_orders.upload_attachment",
  "work_orders.installation_checklist.fill",
  "work_orders.device_serial.fill",
  "work_orders.signal_metrics.fill",

  "installation_verifications.read",
  "installation_verifications.submit",
  "installation_verifications.verify",
  "installation_verifications.reject",

  "invoices.list",
  "invoices.read",
  "invoices.create_manual",
  "invoices.generate_periodic",
  "invoices.generate_auto",
  "invoices.mark_overdue_auto",
  "invoices.cancel",
  "invoices.download",

  "payments.list",
  "payments.read",
  "payments.create_transfer",
  "payments.create_field_collection",
  "payments.verify",
  "payments.reject",
  "payments.void",

  "renewals.list",
  "renewals.read",
  "renewals.create",
  "renewals.cancel_draft",
  "renewals.confirm",

  "cash_categories.list",
  "cash_categories.read",
  "cash_categories.create",
  "cash_categories.update",
  "cash_categories.deactivate",

  "cash_transactions.list",
  "cash_transactions.read",
  "cash_transactions.create_in",
  "cash_transactions.create_out",
  "cash_transactions.update",
  "cash_transactions.delete",
  "cash_transactions.confirm",
  "cash_transactions.report",

  "tickets.list",
  "tickets.read",
  "tickets.create",
  "tickets.assign",
  "tickets.update_status",
  "tickets.comment",
  "tickets.close",

  "notifications.logs.list",
  "notifications.logs.read",
  "notifications.whatsapp.send_h_minus_3",
  "notifications.whatsapp.send_h_0",
  "notifications.whatsapp.send_manual",

  "dashboard.admin.read",
  "dashboard.teknisi.read",
  "dashboard.finance.read",
  "dashboard.customer.read",
  "reports.revenue.read",
  "reports.cashflow.read",
  "reports.receivables.read",
  "reports.technician_performance.read",

  "audit_logs.list",
  "audit_logs.read",

  "system.invoices.generate_auto",
  "system.invoices.mark_overdue",
  "system.notifications.whatsapp.h_minus_3",
  "system.notifications.whatsapp.h_0",
  "system.customer_accounts.provision_on_activation",
] as const;

const humanPermissionKeys = permissionKeys.filter((key) => !key.startsWith("system."));

export const permissions = permissionKeys.map((key) => ({
  key,
  module: key.split(".")[0] ?? "general",
  description: `Permission for ${key}`,
}));

export const rolePermissions: Record<string, readonly string[]> = {
  admin: humanPermissionKeys,
  teknisi: [
    "auth.login",
    "auth.logout",
    "auth.me.read",
    "auth.profile.update",
    "auth.password.change_self",
    "users.list",
    "users.read",
    "roles.list",
    "roles.read",
    "permissions.list",
    "settings.general.read",
    "settings.general.update",
    "prospects.list",
    "prospects.read",
    "prospects.create",
    "prospects.update",
    "prospects.assign_plan",
    "prospects.set_installation_date",
    "prospects.set_coordinates",
    "prospects.set_pppoe_username",
    "prospects.set_pppoe_password",
    "prospects.view_pppoe_password",
    "prospects.copy_pppoe_password",
    "prospects.mark_surveyed",
    "prospects.mark_scheduled_installation",
    "prospects.mark_installed",
    "prospects.mark_cancelled",
    "customers.list",
    "customers.read",
    "customers.update",
    "customers.view_customer_code",
    "customer_addresses.list",
    "customer_addresses.read",
    "customer_addresses.update",
    "service_plans.list",
    "service_plans.read",
    "subscriptions.list",
    "subscriptions.read",
    "subscriptions.view_pppoe_password",
    "subscriptions.copy_pppoe_password",
    "work_orders.list",
    "work_orders.read",
    "work_orders.update",
    "work_orders.close",
    "work_orders.upload_attachment",
    "work_orders.installation_checklist.fill",
    "work_orders.device_serial.fill",
    "work_orders.signal_metrics.fill",
    "installation_verifications.read",
    "installation_verifications.submit",
    "invoices.list",
    "invoices.read",
    "payments.list",
    "payments.read",
    "payments.create_field_collection",
    "renewals.list",
    "renewals.read",
    "renewals.create",
    "renewals.cancel_draft",
    "tickets.list",
    "tickets.read",
    "tickets.create",
    "tickets.update_status",
    "tickets.comment",
    "tickets.close",
    "dashboard.teknisi.read",
    "reports.technician_performance.read",
    "audit_logs.list",
    "audit_logs.read",
  ],
  finance: [
    "auth.login",
    "auth.logout",
    "auth.me.read",
    "auth.profile.update",
    "auth.password.change_self",
    "users.list",
    "users.read",
    "roles.list",
    "roles.read",
    "permissions.list",
    "prospects.list",
    "prospects.read",
    "customers.list",
    "customers.read",
    "customers.view_customer_code",
    "customer_addresses.list",
    "customer_addresses.read",
    "customer_accounts.list",
    "customer_accounts.read",
    "service_plans.list",
    "service_plans.read",
    "subscriptions.list",
    "subscriptions.read",
    "invoices.list",
    "invoices.read",
    "invoices.create_manual",
    "invoices.generate_periodic",
    "invoices.download",
    "payments.list",
    "payments.read",
    "payments.create_transfer",
    "payments.create_field_collection",
    "payments.verify",
    "payments.reject",
    "renewals.list",
    "renewals.read",
    "cash_categories.list",
    "cash_categories.read",
    "cash_categories.create",
    "cash_categories.update",
    "cash_categories.deactivate",
    "cash_transactions.list",
    "cash_transactions.read",
    "cash_transactions.create_in",
    "cash_transactions.create_out",
    "cash_transactions.update",
    "cash_transactions.delete",
    "cash_transactions.confirm",
    "cash_transactions.report",
    "tickets.list",
    "tickets.read",
    "notifications.logs.list",
    "notifications.logs.read",
    "notifications.whatsapp.send_h_minus_3",
    "notifications.whatsapp.send_h_0",
    "dashboard.finance.read",
    "reports.revenue.read",
    "reports.cashflow.read",
    "reports.receivables.read",
    "reports.technician_performance.read",
    "audit_logs.list",
    "audit_logs.read",
  ],
  customer: [
    "auth.login",
    "auth.logout",
    "auth.me.read",
    "auth.profile.update",
    "auth.password.change_self",
    "customers.read",
    "customer_addresses.read",
    "customer_accounts.read",
    "customer_accounts.change_password_self",
    "service_plans.list",
    "service_plans.read",
    "subscriptions.read",
    "invoices.list",
    "invoices.read",
    "invoices.download",
    "payments.list",
    "payments.read",
    "payments.create_transfer",
    "renewals.list",
    "renewals.read",
    "renewals.create",
    "renewals.cancel_draft",
    "tickets.list",
    "tickets.read",
    "tickets.create",
    "tickets.comment",
    "dashboard.customer.read",
  ],
};

export const cashCategories = [
  {
    code: "installation_fee",
    name: "Biaya Instalasi",
    type: "cash_in",
    description: "Pemasukan biaya instalasi pelanggan baru.",
    defaultKeteranganTemplate: "Pemasukan biaya instalasi pelanggan {customer_code}",
  },
  {
    code: "device_sale",
    name: "Penjualan Perangkat",
    type: "cash_in",
    description: "Pemasukan penjualan perangkat atau aksesoris.",
    defaultKeteranganTemplate: "Penjualan perangkat / aksesoris kepada pelanggan",
  },
  {
    code: "subscription_income",
    name: "Pemasukan Langganan",
    type: "cash_in",
    description: "Pemasukan pembayaran tagihan langganan internet.",
    defaultKeteranganTemplate: "Pembayaran langganan pelanggan {customer_code}",
  },
  {
    code: "non_invoice_service_income",
    name: "Pemasukan Jasa Non-Bulanan",
    type: "cash_in",
    description: "Pemasukan jasa di luar tagihan bulanan.",
    defaultKeteranganTemplate: "Pemasukan jasa non-bulanan",
  },
  {
    code: "other_income",
    name: "Pemasukan Lain-Lain",
    type: "cash_in",
    description: "Pemasukan lain-lain.",
    defaultKeteranganTemplate: "Pemasukan lain-lain",
  },
  {
    code: "technician_transport",
    name: "Transport Teknisi",
    type: "cash_out",
    description: "Biaya transport teknisi ke lokasi.",
    defaultKeteranganTemplate: "Biaya transport teknisi ke lokasi {area}",
  },
  {
    code: "tools_material_purchase",
    name: "Pembelian Alat dan Material",
    type: "cash_out",
    description: "Pembelian alat dan material operasional.",
    defaultKeteranganTemplate: "Pembelian alat / material untuk kebutuhan instalasi",
  },
  {
    code: "electricity",
    name: "Biaya Listrik",
    type: "cash_out",
    description: "Biaya listrik.",
    defaultKeteranganTemplate: "Pembayaran biaya listrik periode {period}",
  },
  {
    code: "maintenance",
    name: "Biaya Maintenance",
    type: "cash_out",
    description: "Biaya maintenance perangkat dan jaringan.",
    defaultKeteranganTemplate: "Biaya maintenance jaringan / perangkat",
  },
  {
    code: "administration_expense",
    name: "Biaya Administrasi",
    type: "cash_out",
    description: "ATK, admin, dan operasional kantor.",
    defaultKeteranganTemplate: "Biaya administrasi dan operasional kantor",
  },
  {
    code: "internet_upstream",
    name: "Biaya Upstream Internet",
    type: "cash_out",
    description: "Pembayaran bandwidth atau upstream internet.",
    defaultKeteranganTemplate: "Pembayaran bandwidth / upstream periode {period}",
  },
  {
    code: "rent",
    name: "Biaya Sewa",
    type: "cash_out",
    description: "Sewa kantor, gudang, atau titik perangkat.",
    defaultKeteranganTemplate: "Pembayaran sewa lokasi / gudang / site",
  },
  {
    code: "salary_fee",
    name: "Gaji dan Honor",
    type: "cash_out",
    description: "Gaji, upah, honor, atau insentif.",
    defaultKeteranganTemplate: "Pembayaran gaji / honor / insentif",
  },
  {
    code: "other_expense",
    name: "Pengeluaran Lain-Lain",
    type: "cash_out",
    description: "Pengeluaran lain-lain.",
    defaultKeteranganTemplate: "Pengeluaran lain-lain",
  },
] as const;
